@startuml
'!theme _none_
'!theme amiga
'!theme aws-orange
'!theme black-knight
!theme bluegray
'!theme blueprint
'!theme carbon-gray
'!theme cerulean
'!theme cerulean-outline
'!theme cloudscape-design
'!theme crt-amber
'!theme crt-green
'!theme cyborg
'!theme cyborg-outline
'!theme hacker
'!theme lightgray
'!theme mars
'!theme materia
'!theme materia-outline
'!theme metal
'!theme mimeograph
'!theme minty
'!theme plain
'!theme reddress-darkblue
'!theme reddress-darkgreen
'!theme reddress-darkorange
'!theme reddress-darkred
'!theme reddress-lightblue
'!theme reddress-lightgreen
'!theme reddress-lightorange
'!theme reddress-lightred
'!theme sandstone
'!theme silver
'!theme sketchy
'!theme sketchy-outline
'!theme spacelab
'!theme spacelab-white
'!theme superhero
'!theme superhero-outline
'!theme toy
'!theme united
'!theme vibrant
@enduml
